### ISSUE TITLE
Login button / sql tables

### ISSUE THREAD

**Issue by laughingxman** [Canaan-Creative/Avalon-Management-System#17]
When I click the login button nothing happens, I have everything installed, and verified the sql db is setup. Not seeing the tables being installed into db tho

**Comment by laughingxman** [comment]
brandon@avalon-management-system:/usr/lib/apache2/modules$ amscli  config
Traceback (most recent call last):
  File "/usr/local/bin/amscli", line 498, in <module>
    config(sys.argv[2:])
  File "/usr/local/bin/amscli", line 218, in config
    if argv[1] == '-f':
IndexError: list index out of range

**Comment by laughingxman** [comment]
So I see "amscli adduser" is successfully adding to the database. I am having issues getting "amscli controller" to add a controller  it says invalid everytime.

**Comment by laughingxman** [comment]
Now it doesn't show invalid, but after I add something it doesn't actually add it

**Comment by playisfun60** [comment]
Having same issue

**Comment by archangdcc** [comment]
Each line in the vim editor after running `amscli controller` should match the pattern of https://github.com/Canaan-Creative/Avalon-Management-System/blob/2d69714e37d4474db8f730f800f6e60df71e1990/server/amscli#L298-L302

And lines started with `#` will be ignored.

**Comment by laughingxman** [comment]
Even using the proper pattern it is not taking  the data into the sql db when adding a controller. Any other suggestions?

**Comment by CCGLLC-knc** [comment]
> Each line in the vim editor after running `amscli controller` should match the pattern of
> 
> [Avalon-Management-System/server/amscli](https://github.com/Canaan-Creative/Avalon-Management-System/blob/2d69714e37d4474db8f730f800f6e60df71e1990/server/amscli#L298-L302)
> 
> Lines 298 to 302 in [2d69714](/Canaan-Creative/Avalon-Management-System/commit/2d69714e37d4474db8f730f800f6e60df71e1990)
> 
>  pattern = re.compile( 
>      r'\s*(?P<ip>[0-9a-fA-F.:\[\]]+)\s+' 
>      '(?P<port>[0-9]+)\s+' 
>      '(?P<mods>[0-9]+)\s*', re.X 
>  ) 
> And lines started with `#` will be ignored.

Could you provide some examples?  IP is obvious (e.g. 172.16.4.1).   I presume Port should just be a number with the default being 80?   No clue what Mods referes to.
